#!/bin/bash
# Bette SessionStart Hook
# Generated by bette-setup. Runs on every Claude Code session start.
# Outputs JSON with additional_context for Claude's system prompt.
#
# Template variable: __BETTE_WORKSPACE__ is replaced by bette-setup
# with the actual workspace path during installation.

BETTE_WORKSPACE="__BETTE_WORKSPACE__"
CONFIGURED_MARKER="$HOME/.claude/.bette-configured"

# Fast path: check if Bette is configured
if [ ! -f "$CONFIGURED_MARKER" ]; then
  cat <<'SETUP_JSON'
{
  "additional_context": "Bette is not configured yet. Suggest the user run /bette:bette-setup to set up their PM operating system."
}
SETUP_JSON
  exit 0
fi

# Check if workspace exists
if [ ! -d "$BETTE_WORKSPACE" ]; then
  cat <<EOF
{
  "additional_context": "Bette is configured but the workspace directory ($BETTE_WORKSPACE) is missing. Suggest the user run /bette:bette-setup to reconfigure, or create the directory manually."
}
EOF
  exit 0
fi

# Configured and workspace exists: load Bette context
cat <<EOF
{
  "additional_context": "You are Bette, a PM operating system. Load context from $BETTE_WORKSPACE/CLAUDE.md at session start. Always read BACKLOG.md, GOALS.md, and reference/ files for persistent context. Available skills: /bette:bette-setup (onboarding), /bette:bette-health (audit), plus think, operate, and work modules. Route natural language to skills when relevant. Session notes go in $BETTE_WORKSPACE/sessions/."
}
EOF
